[package]
name = "stf"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
shared-types = { workspace = true }

[dev-dependencies]
k256 = { workspace = true, features = ["ecdsa"] }
hex = { workspace = true }
tiny-keccak = { workspace = true }

[features]
default = ["std"]
std = ["shared-types/std"]
